version: '3.8'

services:
  fastapi_app:
    image: vetri8903/fastapi-app
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - qdrand  
    networks:
      - mongodb_app_network
        
  qdrand:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    networks:
      - mongodb_app_network
 
networks:
  mongodb_app_network:
    driver: bridge